/** Extended ERP modules — purchases, HRM, payroll, manufacturing, accounting, settings. */

export const EXTENDED_API_MODULE_KEYS = [
  'purchaseOrders',
  'goodsReceived',
  'vendorBills',
  'purchasePayments',
  'purchaseReturns',
  'recipes',
  'purchaseRm',
  'departments',
  'designations',
  'attendance',
  'leaveRequests',
  'salaryStructures',
  'payrollRuns',
  'payrollSlips',
  'productionOrders',
  'machineMaintenance',
  'molds',
  'wastage',
  'packing',
  'journals',
  'ledger',
  'dues',
  'crmActivities',
  'wholesaleOrders',
  'users',
  'roles',
  'permissions',
  'documents',
  'companySettings',
  'projects',
  'assets',
  'workflowApprovals',
  'auditLogs',
  'notifications',
  'cashbox',
  'trialBalance',
  'profitLoss',
  'balanceSheet',
  'salarySheet',
] as const;

export type ExtendedApiModule = (typeof EXTENDED_API_MODULE_KEYS)[number];

export const EXTENDED_API_PATHS: Record<ExtendedApiModule, string> = {
  purchaseOrders: '/purchase-orders',
  goodsReceived: '/goods-received',
  vendorBills: '/vendor-bills',
  purchasePayments: '/purchase-payments',
  purchaseReturns: '/purchase-returns',
  recipes: '/recipes',
  purchaseRm: '/purchase-rm',
  departments: '/departments',
  designations: '/designations',
  attendance: '/attendance',
  leaveRequests: '/leave-requests',
  salaryStructures: '/salary-structures',
  payrollRuns: '/payroll-runs',
  payrollSlips: '/payroll-slips',
  productionOrders: '/production-orders',
  machineMaintenance: '/machine-maintenance',
  molds: '/molds',
  wastage: '/wastage',
  packing: '/packing',
  journals: '/journals',
  ledger: '/ledger',
  dues: '/dues',
  crmActivities: '/crm-activities',
  wholesaleOrders: '/wholesale-orders',
  users: '/users',
  roles: '/roles',
  permissions: '/permissions',
  documents: '/documents',
  companySettings: '/company-settings',
  projects: '/projects',
  assets: '/assets',
  workflowApprovals: '/workflow-approvals',
  auditLogs: '/audit-logs',
  notifications: '/notifications',
  cashbox: '/cashbox',
  trialBalance: '/trial-balance',
  profitLoss: '/profit-loss',
  balanceSheet: '/balance-sheet',
  salarySheet: '/salary-sheet',
};

export const EXTENDED_API_LABELS: Record<ExtendedApiModule, string> = {
  purchaseOrders: 'Purchase Orders',
  goodsReceived: 'Goods Received',
  vendorBills: 'Vendor Bills',
  purchasePayments: 'Purchase Payments',
  purchaseReturns: 'Purchase Returns',
  recipes: 'Recipes',
  purchaseRm: 'Purchase RM',
  departments: 'Departments',
  designations: 'Designations',
  attendance: 'Attendance',
  leaveRequests: 'Leave Requests',
  salaryStructures: 'Salary Structures',
  payrollRuns: 'Payroll Runs',
  payrollSlips: 'Payroll Slips',
  productionOrders: 'Production Orders',
  machineMaintenance: 'Machine Maintenance',
  molds: 'Molds',
  wastage: 'Wastage',
  packing: 'Packing',
  journals: 'Journal Entries',
  ledger: 'General Ledger',
  dues: 'Due Management',
  crmActivities: 'CRM Activities',
  wholesaleOrders: 'Wholesale Orders',
  users: 'Users',
  roles: 'Roles',
  permissions: 'Permissions',
  documents: 'Documents',
  companySettings: 'Company Settings',
  projects: 'Projects',
  assets: 'Assets',
  workflowApprovals: 'Workflow Approvals',
  auditLogs: 'Audit Logs',
  notifications: 'Notifications',
  cashbox: 'Cashbox',
  trialBalance: 'Trial Balance',
  profitLoss: 'Profit & Loss',
  balanceSheet: 'Balance Sheet',
  salarySheet: 'Salary Sheet',
};

/** Maps DedicatedModule configId → extended API module key. */
export const LEGACY_CONFIG_API_MODULES: Record<string, ExtendedApiModule> = {
  'purchases-orders': 'purchaseOrders',
  'purchases-goods-received': 'goodsReceived',
  'purchases-bills': 'vendorBills',
  'purchases-payments': 'purchasePayments',
  'purchases-returns': 'purchaseReturns',
  'purchases-recipes': 'recipes',
  'hrm-departments': 'departments',
  'hrm-designations': 'designations',
  'hrm-attendance': 'attendance',
  'hrm-leave': 'leaveRequests',
  'payroll-structures': 'salaryStructures',
  'payroll-runs': 'payrollRuns',
  'payroll-slips': 'payrollSlips',
  'manufacturing-orders': 'productionOrders',
  'manufacturing-machine-maintenance': 'machineMaintenance',
  'manufacturing-mold-management': 'molds',
  'manufacturing-wastage': 'wastage',
  'manufacturing-packing': 'packing',
  'accounting-journals': 'journals',
  'accounting-ledger': 'ledger',
  'accounting-dues': 'dues',
  'crm-activities': 'crmActivities',
  'sales-wholesale': 'wholesaleOrders',
  'settings-users': 'users',
  'settings-roles': 'roles',
  'settings-permissions': 'permissions',
  'settings-documents': 'documents',
  'settings-company': 'companySettings',
  projects: 'projects',
  'asset-management': 'assets',
  'workflow-approvals': 'workflowApprovals',
  notifications: 'notifications',
};

export function getLegacyApiModule(configId: string | undefined): ExtendedApiModule | undefined {
  if (!configId) return undefined;
  return LEGACY_CONFIG_API_MODULES[configId];
}
