'use client';

import {
  listEmployees, createEmployee, updateEmployee, deleteEmployee, getEmployeeMetrics,
  getEmployeeInitialForm, mapEmployeeRowToForm,
  listDepartments, listDesignations, listAttendance, listLeaveRequests,
  listSalaryStructures, listPayrollRuns, listPayrollSlips, crudHrm,
} from '@/lib/services/hrm-service';
import { getSalaryStructureMetrics, formatMoney as payrollMoney } from '@/lib/services/payroll-service';
import { createInState, updateInState, deleteFromState } from '@/lib/services/domain-service';
import { adapter, money, type DedicatedModuleConfig } from './shared';
export const CONFIGS: Record<string, DedicatedModuleConfig> = {
  'hrm-employees': {
    id: 'hrm-employees',
    title: 'Employees',
    subtitle: 'Employee directory and profiles.',
    addLabel: 'Register Employee',
    searchKeys: ['name', 'email', 'department'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'department', label: 'Department' },
      { key: 'designation', label: 'Designation' },
      { key: 'phone', label: 'Phone' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'phone', label: 'Phone', type: 'phone', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'designation', label: 'Designation', type: 'text', required: true },
      { key: 'joiningDate', label: 'Joining Date', type: 'date', required: true },
      { key: 'email', label: 'Email', type: 'email', advanced: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'on-leave'], advanced: true },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => {
      const m = getEmployeeMetrics(rows);
      return [
        { key: 'total', label: 'Total Employees', value: String(m.total) },
        { key: 'active', label: 'Active', value: String(m.active) },
        { key: 'leave', label: 'On Leave', value: String(m.onLeave) },
        { key: 'inactive', label: 'Inactive', value: String(m.inactive) },
        { key: 'payroll', label: 'Monthly Payroll', value: money(m.monthlyPayroll), sub: 'Active staff only' },
      ];
    },
    adapter: adapter({
      list: listEmployees,
      create: createEmployee,
      update: updateEmployee,
      delete: deleteEmployee,
      getInitialForm: getEmployeeInitialForm,
      mapRowToForm: mapEmployeeRowToForm,
    }),
  },
  'hrm-departments': {
    id: 'hrm-departments',
    title: 'Departments',
    subtitle: 'Organizational departments.',
    addLabel: 'Add Department',
    searchKeys: ['name', 'head'],
    columns: [{ key: 'name', label: 'Department' }, { key: 'head', label: 'Head' }, { key: 'status', label: 'Status' }],
    fields: [
      { key: 'name', label: 'Department Name', type: 'text', required: true },
      { key: 'head', label: 'Department Head', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Departments', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('departments', 'DEPT') }),
  },
  'hrm-designations': {
    id: 'hrm-designations',
    title: 'Designations',
    subtitle: 'Job titles and designations.',
    addLabel: 'Add Designation',
    searchKeys: ['title', 'department'],
    columns: [{ key: 'title', label: 'Title' }, { key: 'department', label: 'Department' }, { key: 'status', label: 'Status' }],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Designations', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('designations', 'DES') }),
  },
  'hrm-attendance': {
    id: 'hrm-attendance',
    title: 'Attendance',
    subtitle: 'Daily attendance records.',
    addLabel: 'Record Attendance',
    searchKeys: ['employeeId', 'date'],
    columns: [
      { key: 'date', label: 'Date' },
      { key: 'employeeId', label: 'Employee' },
      { key: 'checkIn', label: 'Check In' },
      { key: 'checkOut', label: 'Check Out' },
      { key: 'workingHours', label: 'Hours' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'employeeId', label: 'Employee ID', type: 'text', required: true },
      { key: 'checkIn', label: 'Check In', type: 'text' },
      { key: 'checkOut', label: 'Check Out', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Present', 'Absent', 'Late', 'On Leave'] },
      { key: 'workingHours', label: 'Working Hours', type: 'number', advanced: true },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'present', label: 'Present Today', value: String(rows.filter((r) => r.status === 'Present').length) },
      { key: 'absent', label: 'Absent', value: String(rows.filter((r) => r.status === 'Absent').length) },
    ],
    adapter: adapter({ ...crudHrm('attendance', 'ATT') }),
  },
  'hrm-leave': {
    id: 'hrm-leave',
    title: 'Leave Management',
    subtitle: 'Leave requests and balances.',
    addLabel: 'New Leave Request',
    searchKeys: ['employee', 'type'],
    columns: [
      { key: 'employee', label: 'Employee' },
      { key: 'type', label: 'Leave Type' },
      { key: 'startDate', label: 'Start' },
      { key: 'endDate', label: 'End' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'employee', label: 'Employee', type: 'text', required: true },
      { key: 'type', label: 'Leave Type', type: 'select', options: ['annual', 'sick', 'casual', 'unpaid'] },
      { key: 'startDate', label: 'Start Date', type: 'date', required: true },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'rejected'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'pending', label: 'Pending Requests', value: String(rows.filter((r) => r.status === 'pending').length) },
      { key: 'approved', label: 'Approved', value: String(rows.filter((r) => r.status === 'approved').length) },
    ],
    adapter: adapter({ ...crudHrm('leaveRequests', 'LV') }),
  },
  'payroll-structures': {
    id: 'payroll-structures',
    title: 'Salary Setup',
    subtitle: 'Manage salary components, deduction rules, and employee assignments.',
    addLabel: 'Add Structure',
    searchKeys: ['name', 'code', 'employeeType'],
    statusTabs: [
      { id: 'all', label: 'All' },
      { id: 'active', label: 'Active' },
      { id: 'inactive', label: 'Inactive' },
    ],
    columns: [
      { key: 'name', label: 'Structure' },
      { key: 'employeeType', label: 'Employee Type' },
      { key: 'payFrequency', label: 'Pay Frequency' },
      { key: 'base', label: 'Base Salary' },
      { key: 'totalFixed', label: 'Total Fixed' },
      { key: 'assignedCount', label: 'Employees' },
      { key: 'effectiveFrom', label: 'Effective From' },
      { key: 'rules', label: 'Rules' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'name', label: 'Structure Name', type: 'text', required: true },
      { key: 'base', label: 'Base Salary', type: 'number', required: true },
      { key: 'allowances', label: 'Allowances', type: 'number' },
      { key: 'deductions', label: 'Default Deductions', type: 'number', advanced: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => {
      const m = getSalaryStructureMetrics(rows);
      return [
        { key: 'total', label: 'Total Structures', value: String(m.total), iconify: 'flat-color-icons:rules' },
        { key: 'active', label: 'Active', value: String(m.active), iconify: 'flat-color-icons:ok' },
        { key: 'assigned', label: 'Employees Assigned', value: String(m.assignedEmployees), iconify: 'flat-color-icons:manager' },
        { key: 'payroll', label: 'Monthly Payroll', value: payrollMoney(m.monthlyPayroll), sub: 'Active structures', iconify: 'flat-color-icons:paid' },
        { key: 'avgBase', label: 'Avg Base Salary', value: payrollMoney(m.avgBase), sub: 'Per active structure', iconify: 'flat-color-icons:currency-exchange' },
      ];
    },
    adapter: adapter({ ...crudHrm('salaryStructures', 'SS') }),
  },
  'payroll-runs': {
    id: 'payroll-runs',
    title: 'Payroll Runs',
    subtitle: 'Process payroll batches.',
    addLabel: 'New Payroll Run',
    searchKeys: ['period'],
    columns: [
      { key: 'period', label: 'Period' },
      { key: 'employees', label: 'Employees' },
      { key: 'totalNet', label: 'Total Net', render: (r) => money(r.totalNet) },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'period', label: 'Pay Period', type: 'text', required: true },
      { key: 'employees', label: 'Employee Count', type: 'number' },
      { key: 'totalNet', label: 'Total Net Pay', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'processing', 'completed'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'runs', label: 'Total Runs', value: String(rows.length) },
      { key: 'completed', label: 'Completed', value: String(rows.filter((r) => r.status === 'completed').length) },
    ],
    adapter: adapter({ ...crudHrm('payrollRuns', 'PR') }),
  },
  'payroll-slips': {
    id: 'payroll-slips',
    title: 'Payslips',
    subtitle: 'Employee payslips.',
    addLabel: 'Generate Payslip',
    searchKeys: ['name', 'id'],
    columns: [
      { key: 'id', label: 'Payslip #' },
      { key: 'name', label: 'Employee' },
      { key: 'base', label: 'Base', render: (r) => money(r.base) },
      { key: 'net', label: 'Net Pay', render: (r) => money(r.net) },
      { key: 'date', label: 'Date' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'name', label: 'Employee', type: 'text', required: true },
      { key: 'base', label: 'Base Salary', type: 'number' },
      { key: 'allowances', label: 'Allowances', type: 'number' },
      { key: 'deductions', label: 'Deductions', type: 'number' },
      { key: 'net', label: 'Net Pay', type: 'number' },
      { key: 'date', label: 'Pay Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'approved', 'paid', 'Disbursed', 'Pending'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'total', label: 'Total Payslips', value: String(rows.length) },
      { key: 'net', label: 'Total Disbursed', value: money(rows.reduce((s, r) => s + Number(r.net ?? 0), 0)) },
    ],
    adapter: adapter({
      list: listPayrollSlips,
      create: (s, p) => createInState(s, 'payroll', p, 'PAY'),
      update: (s, id, p) => updateInState(s, 'payroll', id, p),
      delete: (s, id) => deleteFromState(s, 'payroll', id),
    }),
  },
} as Record<string, DedicatedModuleConfig>;
