'use client';

import { PORT_CONFIGS } from '@/lib/modules/port-configs';
import { summarizeProjects } from '@/lib/services/projects-service';
import { listFromState, createInState, updateInState, deleteFromState } from '@/lib/services/domain-service';
import { crudFactory } from '@/lib/services/manufacturing-service';
import { crudHrm } from '@/lib/services/hrm-service';
import { crmActivityAdapter } from '@/lib/modules/port-adapters';
import { adapter, money, type DedicatedModuleConfig } from './shared';
export const CONFIGS: Record<string, DedicatedModuleConfig> = {
  'crm-activities': {
    ...(PORT_CONFIGS['crm-activities'] as DedicatedModuleConfig),
    kpi: (rows) => [{ key: 'total', label: 'Total Activities', value: String(rows.length) }],
  },
  'sales-wholesale': {
    id: 'sales-wholesale',
    title: 'Wholesale',
    subtitle: 'Wholesale order management.',
    addLabel: 'New Wholesale Order',
    searchKeys: ['buyer', 'id'],
    columns: [
      { key: 'id', label: 'Order #' },
      { key: 'buyer', label: 'Buyer' },
      { key: 'total', label: 'Total', render: (r) => money(r.total) },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'buyer', label: 'Buyer', type: 'text', required: true },
      { key: 'total', label: 'Total', type: 'number', required: true },
      { key: 'qty', label: 'Quantity', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'closed', 'pending', 'cancelled'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'orders', label: 'Total Orders', value: String(rows.length) },
      { key: 'value', label: 'Total Value', value: money(rows.reduce((s, r) => s + Number(r.total ?? 0), 0)) },
    ],
    adapter: adapter({
      list: (s) => listFromState(s, 'wholesaleOrders'),
      create: (s, p) => createInState(s, 'wholesaleOrders', p, 'WS'),
      update: (s, id, p) => updateInState(s, 'wholesaleOrders', id, p),
      delete: (s, id) => deleteFromState(s, 'wholesaleOrders', id),
    }),
  },
  'settings-users': {
    id: 'settings-users',
    title: 'Users',
    subtitle: 'Manage system users and access.',
    addLabel: 'Add User',
    searchKeys: ['name', 'email', 'role'],
    columns: [
      { key: 'name', label: 'User' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'name', label: 'Full Name', type: 'text', required: true },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'role', label: 'Role', type: 'select', options: ['Admin', 'Manager', 'User', 'Viewer'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
      { key: 'phone', label: 'Phone', type: 'phone', advanced: true },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'total', label: 'Total Users', value: String(rows.length) },
      { key: 'active', label: 'Active', value: String(rows.filter((r) => r.status === 'Active').length) },
    ],
    adapter: adapter({ ...crudHrm('users', 'USR') }),
  },
  'settings-roles': {
    id: 'settings-roles',
    title: 'Roles',
    subtitle: 'Define user roles and permissions.',
    addLabel: 'Add Role',
    searchKeys: ['name'],
    columns: [{ key: 'name', label: 'Role' }, { key: 'users', label: 'Users' }, { key: 'status', label: 'Status' }],
    fields: [
      { key: 'name', label: 'Role Name', type: 'text', required: true },
      { key: 'users', label: 'User Count', type: 'number' },
      { key: 'permissions', label: 'Permissions Summary', type: 'textarea', advanced: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Roles', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('roles', 'ROLE') }),
  },
  'settings-permissions': {
    id: 'settings-permissions',
    title: 'Permissions',
    subtitle: 'Module-level access control.',
    addLabel: 'Add Permission',
    searchKeys: ['module'],
    columns: [{ key: 'module', label: 'Module' }, { key: 'access', label: 'Access' }, { key: 'role', label: 'Role' }],
    fields: [
      { key: 'module', label: 'Module', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'access', label: 'Access Level', type: 'select', options: ['none', 'read', 'write', 'admin'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Permission Rules', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('permissions', 'PERM') }),
  },
  'settings-documents': {
    id: 'settings-documents',
    title: 'Documents',
    subtitle: 'Document templates and settings.',
    addLabel: 'Add Document',
    searchKeys: ['name', 'type'],
    columns: [{ key: 'name', label: 'Document' }, { key: 'type', label: 'Type' }, { key: 'status', label: 'Status' }],
    fields: [
      { key: 'name', label: 'Document Name', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['invoice', 'quotation', 'purchase-order', 'payslip'] },
      { key: 'template', label: 'Template ID', type: 'text', advanced: true },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Documents', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('documents', 'DOC') }),
  },
  'settings-company': {
    id: 'settings-company',
    title: 'Company Settings',
    subtitle: 'Company profile and configuration.',
    addLabel: 'Add Setting',
    searchKeys: ['field', 'value'],
    columns: [{ key: 'field', label: 'Field' }, { key: 'value', label: 'Value' }],
    fields: [
      { key: 'field', label: 'Setting Field', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Settings', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('companySettings', 'SET') }),
  },
  'settings-profile': {
    id: 'settings-profile',
    title: 'Profile Settings',
    subtitle: 'User profile preferences.',
    addLabel: 'Add Preference',
    searchKeys: ['field'],
    columns: [{ key: 'field', label: 'Field' }, { key: 'value', label: 'Value' }],
    fields: [
      { key: 'field', label: 'Preference', type: 'text', required: true },
      { key: 'value', label: 'Value', type: 'text', required: true },
    ],
    kpi: (rows) => [{ key: 'total', label: 'Preferences', value: String(rows.length) }],
    adapter: adapter({ ...crudHrm('profileSettings', 'PROF') }),
  },
  'projects': {
    id: 'projects',
    title: 'Projects',
    subtitle: 'Track customer orders, production setup, and delivery milestones.',
    addLabel: 'New Project',
    searchKeys: ['name', 'lead', 'customerName', 'projectId'],
    statusTabs: [
      { id: 'all', label: 'All' },
      { id: 'active', label: 'Active' },
      { id: 'draft', label: 'Draft' },
    ],
    columns: [
      { key: 'name', label: 'Project' },
      { key: 'lead', label: 'Lead' },
      { key: 'progress', label: 'Progress' },
      { key: 'health', label: 'Health' },
      { key: 'priority', label: 'Priority' },
      { key: 'deadline', label: 'Deadline' },
      { key: 'budget', label: 'Value' },
    ],
    fields: [
      { key: 'name', label: 'Project Name', type: 'text', required: true },
      { key: 'lead', label: 'Project Lead', type: 'text' },
      { key: 'progress', label: 'Progress %', type: 'number' },
      { key: 'health', label: 'Health', type: 'select', options: ['On Track', 'At Risk', 'Delayed', 'green', 'amber', 'red'] },
      { key: 'deadline', label: 'Deadline', type: 'date' },
      { key: 'budget', label: 'Budget', type: 'number', advanced: true },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => summarizeProjects(rows),
    adapter: adapter({
      list: (s) => listFromState(s, 'projects').map((row) => ({
        ...row,
        status: row.status ?? 'active',
      })),
      create: (s, p) => createInState(s, 'projects', p, 'PRJ'),
      update: (s, id, p) => updateInState(s, 'projects', id, p),
      delete: (s, id) => deleteFromState(s, 'projects', id),
    }),
  },
  'asset-management': {
    id: 'asset-management',
    title: 'Asset Management',
    subtitle: 'Track fixed assets and depreciation.',
    addLabel: 'Add Asset',
    searchKeys: ['asset', 'category'],
    columns: [
      { key: 'asset', label: 'Asset' },
      { key: 'category', label: 'Category' },
      { key: 'value', label: 'Value', render: (r) => money(r.value) },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'asset', label: 'Asset Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'value', label: 'Value', type: 'number' },
      { key: 'purchaseDate', label: 'Purchase Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'disposed', 'maintenance'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'total', label: 'Total Assets', value: String(rows.length) },
      { key: 'value', label: 'Total Value', value: money(rows.reduce((s, r) => s + Number(r.value ?? 0), 0)) },
    ],
    adapter: adapter({ ...crudFactory('assets', 'AST') }),
  },
  'workflow-approvals': {
    id: 'workflow-approvals',
    title: 'Workflow Approvals',
    subtitle: 'Pending approval requests.',
    addLabel: 'New Request',
    searchKeys: ['item', 'requester', 'module'],
    statusTabs: [
      { id: 'all', label: 'All' },
      { id: 'pending', label: 'Pending' },
      { id: 'approved', label: 'Approved' },
      { id: 'rejected', label: 'Rejected' },
    ],
    columns: [
      { key: 'item', label: 'Item' },
      { key: 'requester', label: 'Requester' },
      { key: 'module', label: 'Module' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'item', label: 'Item', type: 'text', required: true },
      { key: 'requester', label: 'Requester', type: 'text' },
      { key: 'module', label: 'Module', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'rejected'] },
      { key: 'notes', label: 'Notes', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'pending', label: 'Pending', value: String(rows.filter((r) => r.status === 'pending').length) },
      { key: 'approved', label: 'Approved', value: String(rows.filter((r) => r.status === 'approved').length) },
    ],
    hideDefaultRowActions: (row) => String(row.refType) === 'purchase_rm_order',
    adapter: adapter({ ...crudFactory('approvals', 'APR') }),
  },
  'notifications': {
    id: 'notifications',
    title: 'Notifications',
    subtitle: 'System notifications and alerts.',
    addLabel: 'Add Notification',
    searchKeys: ['title'],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'time', label: 'Time' },
      { key: 'type', label: 'Type' },
      { key: 'status', label: 'Status' },
    ],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'time', label: 'Time', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['info', 'warning', 'success', 'error'] },
      { key: 'status', label: 'Status', type: 'select', options: ['unread', 'read'] },
      { key: 'message', label: 'Message', type: 'textarea', advanced: true },
    ],
    kpi: (rows) => [
      { key: 'unread', label: 'Unread', value: String(rows.filter((r) => r.status === 'unread').length) },
      { key: 'total', label: 'Total', value: String(rows.length) },
    ],
    adapter: adapter({ ...crudFactory('notifications', 'NTF') }),
  },
} as Record<string, DedicatedModuleConfig>;
