import type { NextConfig } from 'next';

const htmlRedirects = [
  ['index.html', '/login'],
  ['dashboard.html', '/dashboard'],
  ['crm-customers.html', '/crm/customers'],
  ['crm-leads.html', '/crm/leads'],
  ['crm-deals.html', '/crm/deals'],
  ['crm-complaints.html', '/crm/complaints'],
  ['crm-activities.html', '/crm/activities'],
  ['sales-quotations.html', '/sales/quotations'],
  ['sales-orders.html', '/sales/orders'],
  ['sales-deliveries.html', '/sales/deliveries'],
  ['sales-dispatch.html', '/sales/dispatch'],
  ['sales-invoices.html', '/sales/invoices'],
  ['sales-payments.html', '/sales/payments'],
  ['sales-returns.html', '/sales/returns'],
  ['sales-pos.html', '/sales/pos'],
  ['sales-wholesale.html', '/sales/wholesale'],
  ['inventory-products.html', '/inventory/products'],
  ['inventory-raw-materials.html', '/inventory/raw-materials'],
  ['inventory-stock-in.html', '/inventory/stock-in'],
  ['inventory-stock-out.html', '/inventory/stock-out'],
  ['inventory-transfers.html', '/inventory/transfers'],
  ['inventory-adjustments.html', '/inventory/adjustments'],
  ['inventory-warehouses.html', '/inventory/warehouses'],
  ['inventory-categories.html', '/inventory/categories'],
  ['inventory-units.html', '/inventory/units'],
  ['purchases-suppliers.html', '/purchases/suppliers'],
  ['purchases-orders.html', '/purchases/orders'],
  ['purchases-goods-received.html', '/purchases/goods-received'],
  ['purchases-bills.html', '/purchases/bills'],
  ['purchases-payments.html', '/purchases/payments'],
  ['purchases-returns.html', '/purchases/returns'],
  ['purchases-recipes.html', '/purchases/recipes'],
  ['manufacturing-orders.html', '/manufacturing/orders'],
  ['manufacturing-bom.html', '/manufacturing/bom'],
  ['manufacturing-machine-maintenance.html', '/manufacturing/machine-maintenance'],
  ['manufacturing-mold-management.html', '/manufacturing/mold-management'],
  ['manufacturing-wastage.html', '/manufacturing/wastage'],
  ['manufacturing-packing.html', '/manufacturing/packing'],
  ['accounting-dues.html', '/accounting/dues'],
  ['accounting-receivables.html', '/accounting/receivables'],
  ['accounting-payables.html', '/accounting/payables'],
  ['accounting-journals.html', '/accounting/journals'],
  ['accounting-ledger.html', '/accounting/ledger'],
  ['accounting-trial.html', '/accounting/trial'],
  ['accounting-pl.html', '/accounting/pl'],
  ['accounting-balance.html', '/accounting/balance'],
  ['hrm-employees.html', '/hrm/employees'],
  ['hrm-departments.html', '/hrm/departments'],
  ['hrm-designations.html', '/hrm/designations'],
  ['hrm-attendance.html', '/hrm/attendance'],
  ['hrm-leave.html', '/hrm/leave'],
  ['payroll-structures.html', '/payroll/structures'],
  ['payroll-runs.html', '/payroll/runs'],
  ['payroll-slips.html', '/payroll/slips'],
  ['reports-sales.html', '/reports/sales'],
  ['reports-purchases.html', '/reports/purchases'],
  ['reports-inventory.html', '/reports/inventory'],
  ['reports-customers.html', '/reports/customers'],
  ['reports-suppliers.html', '/reports/suppliers'],
  ['reports-financial.html', '/reports/financial'],
  ['reports-hr.html', '/reports/hr'],
  ['settings-users.html', '/settings/users'],
  ['settings-roles.html', '/settings/roles'],
  ['settings-permissions.html', '/settings/permissions'],
  ['settings-documents.html', '/settings/documents'],
  ['settings-company.html', '/settings/company'],
  ['settings-audit-logs.html', '/settings/audit-logs'],
  ['settings-profile.html', '/settings/profile'],
  ['projects.html', '/projects'],
  ['asset-management.html', '/asset-management'],
  ['workflow-approvals.html', '/workflow-approvals'],
  ['notifications.html', '/notifications'],
  ['super-admin.html', '/super-admin'],
  ['design-system.html', '/design-system'],
] as const;

const nextConfig: NextConfig = {
  async redirects() {
    return htmlRedirects.flatMap(([html, destination]) => [
      { source: `/${html}`, destination, permanent: false },
    ]);
  },
  images: {
    remotePatterns: [],
    unoptimized: true,
  },
};

export default nextConfig;
